name: kokok_pay
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <=3.10.5'
#  sdk: '>=2.19.0-421.0.dev <=3.8.0-1.0.pre.32'
#  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.0.16
  get_it: ^7.2.0
  lottie: ^2.1.0
  path_provider: ^2.0.11
  image_picker: ^0.8.6
  retrofit: ^4.0.1
  analyzer: ^5.12.0
  dio: ^5.2.1+1
  dartz: ^0.10.1
  freezed: ^2.3.2
  logger: ^1.1.0
  intl: ^0.18.0
  connectivity_plus: ^4.0.1
  json_annotation: ^4.7.0
  flutter_udid: ^2.0.1
  country_picker: ^2.0.19
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  flutter_html: ^3.0.0-alpha.6
  package_info_plus: ^4.0.2
  firebase_core: ^2.5.0
  firebase_messaging: ^14.2.2
  flutter_local_notifications: ^14.1.1
  device_info_plus: ^9.0.2
  encrypt: ^5.0.1
  crypto: ^3.0.2
  local_auth: ^2.1.3
  qr_flutter: ^4.0.0
  http: ^0.13.5
  share_plus: ^7.0.2
  mobile_scanner: ^3.3.0
  awesome_card: ^1.1.7
  fluttercontactpicker: ^4.7.0
  image_gallery_saver: '^2.0.3'

dependency_overrides:
  # Override for `flutter_local_notifications`:
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.1+1
  build_runner: ^2.3.3
  json_serializable: ^6.5.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # Other config...

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/certificate/public_key.pem
#    - assets/images/login_bg.png
#    - assets/images/home_background.jpg
#    - assets/images/placeholder.jpg
#    - assets/images/lao_qr_logo.png
#    - assets/images/home_qr.png
#    - assets/certificate/
    - assets/images/
    - assets/bank/
    - assets/lottie/
    - assets/lottie/dark/
    - assets/resource/
    - assets/resource/1.5x/
    - assets/resource/2.0x/
    - assets/resource/3.0x/
    - assets/resource/4.0x/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 800
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-light.ttf
          weight: 400

    - family: Mukta
      fonts:
        - asset: assets/fonts/mukta/Mukta-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/mukta/Mukta-Bold.ttf
          weight: 800
        - asset: assets/fonts/mukta/Mukta-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/mukta/Mukta-Medium.ttf
          weight: 600
        - asset: assets/fonts/mukta/Mukta-Regular.ttf
          weight: 500
        - asset: assets/fonts/mukta/Mukta-Light.ttf
          weight: 400
        - asset: assets/fonts/mukta/Mukta-ExtraLight.ttf
          weight: 300

    - family: OpenSans
      fonts:
        - asset: assets/fonts/opensans/OpenSans-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/opensans/OpenSans-Bold.ttf
          weight: 800
        - asset: assets/fonts/opensans/OpenSans-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/opensans/OpenSans-Medium.ttf
          weight: 600
        - asset: assets/fonts/opensans/OpenSans-Regular.ttf
          weight: 500
        - asset: assets/fonts/opensans/OpenSans-Light.ttf
          weight: 400

    - family: FaceIcon
      fonts:
        - asset: assets/icons/FaceIcon.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
